
Sistema -> 25/11/2012 - 22:43:26
	ce.model.dao.RepositorioCategoria.excluir(): com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`estoque`.`produto`, CONSTRAINT `produto_fkCodCateg` FOREIGN KEY (`codCateg`) REFERENCES `categoria` (`CodCateg`))
joao.souza -> 25/11/2012 - 22:43:26
	ce.model.regra.ControladorCategoria.excluir(): Não é possível excluir a entrada informada, pois a mesma
 está sendo usanda por um ou mais produto!
Sistema -> 25/11/2012 - 22:46:37
	ce.model.dao.RepositorioCategoria.excluir(): com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`estoque`.`produto`, CONSTRAINT `produto_fkCodCateg` FOREIGN KEY (`codCateg`) REFERENCES `categoria` (`CodCateg`))
joao.souza -> 25/11/2012 - 22:46:37
	ce.model.regra.ControladorCategoria.excluir(): Não é possível excluir a categoria informada, pois a mesma
 está sendo usanda por um ou mais produto!
Sistema -> 25/11/2012 - 22:48:07
	ce.model.dao.RepositorioCategoria.excluir(): com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`estoque`.`produto`, CONSTRAINT `produto_fkCodCateg` FOREIGN KEY (`codCateg`) REFERENCES `categoria` (`CodCateg`))
joao.souza -> 25/11/2012 - 22:48:07
	ce.model.regra.ControladorCategoria.excluir(): Não é possível excluir a categoria informada, pois a mesma
 está sendo usanda por um ou mais produto!
root -> 27/11/2012 - 17:43:46
	ce.util.GerenciadorConexao.conectar(): java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
joao.souza -> 27/11/2012 - 17:43:46
	ce.model.regra.ControladorUsuario.validarLogin(): No momento não é possível validar o login.
adm.sys -> 02/12/2012 - 20:40:02
	ce.model.regra.ControladorUsuario.validarLogin(): Senha inválida!
adm.sys -> 02/12/2012 - 20:40:11
	ce.model.regra.ControladorUsuario.validarLogin(): Senha inválida!
root -> 03/12/2012 - 11:57:15
	ce.util.GerenciadorConexao.conectar(): java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
joao.souza -> 03/12/2012 - 11:57:15
	ce.model.regra.ControladorUsuario.validarLogin(): No momento não é possível validar o login.
Sistema -> 03/12/2012 - 11:57:46
	ce.model.dao.RepositorioFornecedor.pesquisar(): java.sql.SQLException: Column 'codProd' not found.
joao.souza -> 03/12/2012 - 11:57:46
	ce.model.regra.ControladorFornecedor.pesquisar(): Erro ao tentar pesquisar fornecedor.
Sistema -> 03/12/2012 - 12:47:38
	ce.model.dao.RepositorioFornecedor.pesquisar(): com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after statement closed.
joao.souza -> 03/12/2012 - 12:47:38
	ce.model.regra.ControladorFornecedor.pesquisar(): Erro ao tentar pesquisar fornecedor.
Sistema -> 03/12/2012 - 12:48:14
	ce.model.dao.RepositorioFornecedor.pesquisar(): com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after statement closed.
joao.souza -> 03/12/2012 - 12:48:14
	ce.model.regra.ControladorFornecedor.pesquisar(): Erro ao tentar pesquisar fornecedor.
Sistema -> 03/12/2012 - 12:48:26
	ce.model.dao.RepositorioFornecedor.pesquisar(): com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after statement closed.
joao.souza -> 03/12/2012 - 12:48:26
	ce.model.regra.ControladorFornecedor.pesquisar(): Erro ao tentar pesquisar fornecedor.
Sistema -> 04/12/2012 - 21:44:47
	ce.model.dao.RepositorioProduto.listar(): com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'fp.nome' in 'order clause'
joao.souza -> 04/12/2012 - 21:44:47
	ce.model.regra.ControladorProduto.listar(): Erro ao tentar listar produto.
joao.souza -> 05/12/2012 - 09:14:39
	ce.model.regra.ControladorFornecedor.validarDados(): O campo nome deve ser preenchido.
joao.souza -> 05/12/2012 - 09:17:50
	ce.model.regra.ControladorFornecedor.validarDados(): O campo nome deve ser preenchido.
joao.souza -> 05/12/2012 - 09:17:56
	ce.model.regra.ControladorFornecedor.validarDados(): O campo nome deve ser preenchido.
joao.souza -> 05/12/2012 - 09:21:20
	ce.model.regra.ControladorFornecedor.validarDados(): O campo nome deve ser preenchido.
joao.souza -> 05/12/2012 - 09:21:39
	ce.model.regra.ControladorUsuario.validarLogin(): Senha inválida!
joao.souza -> 05/12/2012 - 09:21:51
	ce.model.regra.ControladorFornecedor.validarDados(): CNPJ inválido.
Sistema -> 05/12/2012 - 20:54:02
	ce.model.dao.RepositorioFornecedor.excluir(): com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`estoque`.`fornxprod`, CONSTRAINT `fornxprod_fkCodForn` FOREIGN KEY (`codForn`) REFERENCES `fornecedor` (`codForn`))
joao.souza -> 05/12/2012 - 20:54:02
	ce.model.regra.ControladorFornecedor.excluir(): Não é possível excluir o fornecedor informado, pois o mesmo
 está sendo usando em uma ou mais entrada e/ou saída!
root -> 08/12/2012 - 23:50:20
	ce.util.GerenciadorConexao.conectar(): java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
joao.souza -> 08/12/2012 - 23:50:20
	ce.model.regra.ControladorUsuario.validarLogin(): No momento não é possível validar o login.
joao.souza -> 09/12/2012 - 16:20:24
	ce.model.regra.ControladorUsuario.validarLogin(): Senha inválida!
Sistema -> 09/12/2012 - 19:31:33
	ce.model.dao.RepositorioEntrada.pesquisarNoPeriodo(): java.text.ParseException: Unparseable date: "01/11/2012"
joao.souza -> 09/12/2012 - 19:31:33
	ce.model.regra.ControladorEntrada.pesquisar(): Erro ao tentar pesquisar entrada.
joao.souza -> 09/12/2012 - 21:12:01
	ce.model.regra.ControladorUsuario.validarDados(): Campo com valor inválido!
joao.souza -> 09/12/2012 - 21:12:42
	ce.model.regra.ControladorUsuario.validarDados(): Campo com valor inválido!
joao.souza -> 09/12/2012 - 21:12:57
	ce.model.regra.ControladorUsuario.validarDados(): Campo com valor inválido!
joao.souza -> 09/12/2012 - 21:15:29
	ce.model.regra.ControladorUsuario.validarDados(): Campo com valor inválido! [nome]
joao.souza -> 09/12/2012 - 21:16:30
	ce.model.regra.ControladorUsuario.validarDados(): Campo com valor inválido!
A senha deve ter seis ou mais caracteres.
joao.souza -> 09/12/2012 - 21:16:45
	ce.model.regra.ControladorUsuario.validarDados(): Campo com valor inválido!
A senha deve ter seis ou mais caracteres.
joao.souza -> 09/12/2012 - 21:17:00
	ce.model.regra.ControladorUsuario.validarDados(): Campo com valor inválido!
A senha deve ter seis ou mais caracteres.
joao.souza -> 09/12/2012 - 21:20:51
	ce.model.regra.ControladorUsuario.validarDados(): Campo com valor inválido!
A senha deve ter seis ou mais caracteres.
joao.souza -> 09/12/2012 - 21:21:16
	ce.model.regra.ControladorUsuario.validarLogin(): Senha inválida!
joao.souza -> 09/12/2012 - 21:21:18
	ce.model.regra.ControladorUsuario.validarLogin(): Senha inválida!
joao.souza -> 09/12/2012 - 21:21:35
	ce.model.regra.ControladorUsuario.validarLogin(): Senha inválida!
root -> 09/12/2012 - 19:23:06
	ce.util.GerenciadorConexao.conectar(): java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
joao.souza -> 09/12/2012 - 19:23:06
	ce.model.regra.ControladorUsuario.validarLogin(): No momento não é possível validar o login.
